In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv(r'D:\batch -3\Machine learning project\Project 22 Mental Health Prediction\Mental Health Dataset.csv')
df.shape

(292364, 17)

In [4]:
df.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [5]:
df.shape

(292364, 17)

In [6]:
df.isnull().sum()

Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
self_employed              5202
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

In [7]:
numeric_columns = df.select_dtypes(include=['number']).columns
non_numeric_columns = df.select_dtypes(exclude=['number']).columns

In [8]:
numeric_columns

Index([], dtype='object')

In [9]:
non_numeric_columns

Index(['Timestamp', 'Gender', 'Country', 'Occupation', 'self_employed',
       'family_history', 'treatment', 'Days_Indoors', 'Growing_Stress',
       'Changes_Habits', 'Mental_Health_History', 'Mood_Swings',
       'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
       'mental_health_interview', 'care_options'],
      dtype='object')

In [10]:
df = df.dropna(how='any')

In [11]:
df.isnull().sum()

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64

In [12]:
for col in non_numeric_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [13]:
df.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
5,8/27/2014 11:49,Female,Poland,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Not sure
6,8/27/2014 11:51,Female,Australia,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
7,8/27/2014 11:52,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No

In [14]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
columns_to_encode = [
    'Gender', 'Occupation', 'self_employed', 'family_history', 'treatment',
    'Days_Indoors', 'Growing_Stress', 'Changes_Habits', 'Mental_Health_History',
    'Mood_Swings', 'Coping_Struggles', 'Work_Interest', 'Social_Weakness',
    'mental_health_interview', 'care_options', 'Country'
]

for column in columns_to_encode:
    df[column] = label_encoder.fit_transform(df[column])

In [15]:
df.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
3,8/27/2014 11:37,0,34,1,0,1,1,0,2,1,2,2,0,1,2,0,2
4,8/27/2014 11:43,0,34,1,0,1,1,0,2,1,2,2,0,1,2,1,2
5,8/27/2014 11:49,0,25,1,0,0,1,0,2,1,2,2,0,1,2,0,1
6,8/27/2014 11:51,0,0,1,0,1,1,0,2,1,2,2,0,1,2,1,1
7,8/27/2014 11:52,0,34,1,0,0,0,0,2,1,2,2,0,1,2,1,0

In [16]:
df=df.drop('Timestamp',axis=1)

In [17]:
df=df.drop('Country',axis=1)

In [18]:
df.head()

,Gender,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
3,0,1,0,1,1,0,2,1,2,2,0,1,2,0,2
4,0,1,0,1,1,0,2,1,2,2,0,1,2,1,2
5,0,1,0,0,1,0,2,1,2,2,0,1,2,0,1
6,0,1,0,1,1,0,2,1,2,2,0,1,2,1,1
7,0,1,0,0,0,0,2,1,2,2,0,1,2,1,0

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
x = df.drop(columns=['treatment'])
y = df['treatment']

In [20]:
print(x)

        Gender  Occupation  self_employed  family_history  Days_Indoors  \
3            0           1              0               1             0
4            0           1              0               1             0
5            0           1              0               0             0
6            0           1              0               1             0
7            0           1              0               0             0
...        ...         ...            ...             ...           ...
292359       1           0              1               1             1
292360       1           0              0               1             1
292361       1           0              0               1             1
292362       1           0              0               1             1
292363       1           0              0               1             1

        Growing_Stress  Changes_Habits  Mental_Health_History  Mood_Swings  \
3                    2               1                      2            2
4                    2               1                      2            2
5                    2               1                      2            2
6                    2               1                      2            2
7                    2               1                      2            2
...                ...             ...                    ...          ...
292359               1               0                      1            1
292360               1               0                      1            1
292361               1               0                      1            1
292362               1               0                      1            1
292363               1               0                      1            1

        Coping_Struggles  Work_Interest  Social_Weakness  \
3                      0              1                2
4                      0              1                2
5                      0              1                2
6                      0              1                2
7                      0              1                2
...                  ...            ...              ...
292359                 1              1                0
292360                 1              1                0
292361                 1              1                0
292362                 1              1                0
292363                 1              1                0

        mental_health_interview  care_options
3                             0             2
4                             1             2
5                             0             1
6                             1             1
7                             1             0
...                         ...           ...
292359                        0             1
292360                        1             2
292361                        1             0
292362                        1             2
292363                        1             2

[287162 rows x 14 columns]

In [21]:
print(x.shape)

(287162, 14)

In [22]:
print(y)

3         1
4         1
5         1
6         1
7         0
         ..
292359    1
292360    1
292361    0
292362    1
292363    1
Name: treatment, Length: 287162, dtype: int32

In [23]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=2)
model = RandomForestClassifier()
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [24]:
# accuracy on training data
xtrain_prediction = model.predict(xtrain)
training_data_accuracy = accuracy_score(ytrain, xtrain_prediction)

print('Accuracy on training data = ', training_data_accuracy)

Accuracy on training data =  0.723848534577698

In [25]:
# accuracy on test data
xtest_prediction = model.predict(xtest)
test_data_accuracy = accuracy_score( xtest_prediction, ytest)

print('Accuracy on test data = ', test_data_accuracy)

Accuracy on test data =  0.6956105374958648

In [26]:
# Evaluate the model
conf_matrix = confusion_matrix(ytest, xtest_prediction)
class_report = classification_report(ytest, xtest_prediction)

In [27]:
print("\nClassification Report:\n", class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.63      0.67     28561
           1       0.68      0.76      0.71     28872

    accuracy                           0.70     57433
   macro avg       0.70      0.70      0.69     57433
weighted avg       0.70      0.70      0.69     57433

In [28]:
print("\nClassification Report:\n", conf_matrix)

Classification Report:
 [[18133 10428]
 [ 7054 21818]]

In [29]:
model = GradientBoostingClassifier(random_state=42)
model.fit(xtrain, ytrain)

GradientBoostingClassifier(random_state=42)

In [30]:
xtest_prediction = model.predict(xtest)
test_data_accuracy = accuracy_score( xtest_prediction, ytest)

print('Accuracy on test data = ', test_data_accuracy)

Accuracy on test data =  0.7191335991503143

In [31]:
input_data = (0,1,0,1,0,2,1,2,2,0,1,2,0,2)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for one datapoint
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 1):
  print('The person is Mental Health')

else:
  print('The person is not Mental Health')

c:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(

ValueError: could not convert string to float: 'Female'

In [123]:
import pickle
     

filename = 'Mental health prediction.sav'
pickle.dump(model, open(filename, 'wb'))
     

# loading the saved model
loaded_model = pickle.load(open('Mental health prediction.sav', 'rb'))

for column in df.columns:
    print(column)

Gender
Occupation
self_employed
family_history
treatment
Days_Indoors
Growing_Stress
Changes_Habits
Mental_Health_History
Mood_Swings
Coping_Struggles
Work_Interest
Social_Weakness
mental_health_interview
care_options